version: "3"

services:
  db-mysql:
    image: mysql
    container_name: test_db
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306
    networks:
      - springboot-mysql-net
  test-app:
    container_name: test_app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      - db-mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/mydb?useSSL=false&allowPublicKeyRetrievla=true&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - springboot-mysql-net

networks:
  springboot-mysql-net: